name: sirius

services:
  sqlserver:
    #image: mcr.microsoft.com/mssql/server:2017-latest
    #image: mcr.microsoft.com/mssql/server:2019-latest
    image: mcr.microsoft.com/mssql/server:2022-latest
    #image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=Developer
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - net01

  app:
    build:
      context: C:/Users/pheli/Desktop/github/data-engineering/projects/project-10/infra/apps
      #dockerfile: Dockerfile.app
      dockerfile: Dockerfile
    container_name: apps
    volumes:
      - data-quality:/projeto-dq
    depends_on:
      - sqlserver
    networks:
      - net01

volumes:
  sqlserver_data:
  data-quality:

networks:
  net01:

# referência da imagem dessa versão do SQL Server (2022): https://learn.microsoft.com/pt-br/sql/linux/quickstart-install-connect-docker?view=sql-server-linux-ver16&preserve-view=true&tabs=cli&pivots=cs1-bash#pullandrun2022

# referência de outras imagens:
  # 2017: https://learn.microsoft.com/pt-br/sql/linux/quickstart-install-connect-docker?view=sql-server-linux-2017&preserve-view=true&tabs=cli&pivots=cs1-bash#pullandrun2017
  # 2019: https://learn.microsoft.com/pt-br/sql/linux/quickstart-install-connect-docker?view=sql-server-linux-ver15&preserve-view=true&tabs=cli&pivots=cs1-bash#pullandrun2019
  # 2025: https://learn.microsoft.com/pt-br/sql/linux/quickstart-install-connect-docker?view=sql-server-linux-ver17&preserve-view=true&tabs=cli&pivots=cs1-bash#pullandrun2025