lab9:
  outputs:
    prod:
      dataset: dsadwlab9
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /dsa/chave/dsalab9-0b65981268a7.json
      location: US
      method: service-account
      priority: interactive
      project: lab9
      threads: 1
      type: bigquery
  target: prod