name: database-bind-mount

services:
  sqlserver:
    #image: mcr.microsoft.com/mssql/server:2017-latest
    #image: mcr.microsoft.com/mssql/server:2019-latest
    image: mcr.microsoft.com/mssql/server:2022-latest
    #image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: sqlserver-bm
    ports:
      - "1433:1433"
    environment:
      # Variáveis para configurações no ambiente: https://learn.microsoft.com/pt-br/sql/linux/sql-server-linux-configure-environment-variables?view=sql-server-ver17
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=Developer
    volumes:
    ### Essa é uma expansão de variável com fallback (padrão do Docker Compose)
    ### Se (SQLSERVER_PROJ_DIR) estiver definido no arquivo (.env), ele será usado
    ### Caso contrário (:-.), será usado o diretório atual (.) como base
    ### Se formos avaliar onde está caindo localmente (host), está indo para (./infra/database), visto que temos o arquivo (.env) configurado
    ### Se formos avaliar onde está caindo no container (destino), está indo para (/var/opt/mssql), configurado diretamente nesse bloco
      #- sqlserver_data:/var/opt/mssql
      - ${SQLSERVER_PROJ_DIR:-.}/sqlserver_data:/var/opt/mssql
    networks:
      - net01

#volumes:
  #sqlserver_data:

networks:
  net01:

# referência da imagem dessa versão do SQL Server (2022): https://learn.microsoft.com/pt-br/sql/linux/quickstart-install-connect-docker?view=sql-server-linux-ver16&preserve-view=true&tabs=cli&pivots=cs1-bash#pullandrun2022

# referência de outras imagens:
  # 2017: https://learn.microsoft.com/pt-br/sql/linux/quickstart-install-connect-docker?view=sql-server-linux-2017&preserve-view=true&tabs=cli&pivots=cs1-bash#pullandrun2017
  # 2019: https://learn.microsoft.com/pt-br/sql/linux/quickstart-install-connect-docker?view=sql-server-linux-ver15&preserve-view=true&tabs=cli&pivots=cs1-bash#pullandrun2019
  # 2025: https://learn.microsoft.com/pt-br/sql/linux/quickstart-install-connect-docker?view=sql-server-linux-ver17&preserve-view=true&tabs=cli&pivots=cs1-bash#pullandrun2025