apiVersion: v1
kind: Service
metadata:
  name: ai-streamlit-service
spec:
  type: NodePort
  selector:
    app: ai-streamlit
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
      nodePort: 30001
